### ISSUE TITLE
DNU because CZPillarDocBuilder is Undeclared in ETPublicationsPlugin>>exportInto: 

### ISSUE THREAD

**Issue by tinchodias** [guillep/ecstatic#6]
Hi. Just did setup ecstatic from scratch after a while (maybe since December) and I found this issue when running `ecstatic generate` on my personal website. May be some change in Pillar and/or Citezen is the cause. 

Still didn't investigate... any clue? Can you reproduce with your site @guillep ?

Cheers

**Comment by Ducasse** [comment]
> On 20 Apr 2016, at 05:53, Martín Dias notifications@github.com wrote:
> 
> Hi. Just did setup ecstatic from scratch after a while (maybe since December) and I found this issue when running ecstatic generate on my personal website. May be some change in Pillar and/or Citezen is the cause.

Probably. 
I should check CZ because soemthing strange happened with the build.
if you have a look and find it let me know. 

> Still didn't investigate... any clue? Can you reproduce with your site @guillep https://github.com/guillep ?
> 
> Cheers
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/guillep/ecstatic/issues/6

---

Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France

**Comment by tinchodias** [comment]
Fixed in master: Upgraded Citezen from 2.2 to 2.6.

https://github.com/guillep/ecstatic/commit/a99032adf1b926872e0a73afacd5f128630bac1e
